#Config File example
save_dir: /content/drive/MyDrive/workspace/synthdata/ELG4960_Out/2/nanodet-m_autoaug_modmod_verify
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: /content/drive/MyDrive/Synt data test/211102/data/
    ann_path: /content/drive/MyDrive/Synt data test/211102/data/defect_annotations.json
    input_size: [1024,96] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
#      brightness: 0.2
#      contrast: [0.8, 1.2]
#      saturation: [0.8, 1.2]
      autoaug_value: {'a1': 0.08101963251829147,
                     'a10': 0.21826782822608948,
                     'a11': 0.10481764376163483,
                     'a12': 0.6672841906547546,
                     'a2': 0.12276199460029602,
                     'a3': 0.21467134356498718,
                     'a4': 0.04544099420309067,
                     'a5': 0.2710273265838623,
                     'a6': -0.18187099695205688,
                     'a7': -0.018729938194155693,
                     'a8': -0.2271868735551834,
                     'a9': 0.24968217313289642,
                     'b0': 0.041343141347169876,
                     'b1': 0.18310876190662384,
                     'b10': 0.011901714839041233,
                     'b11': 0.07119786739349365,
                     'b12': -0.2891852557659149,
                     'b2': 0.05530325695872307,
                     'b3': 0.1800641119480133,
                     'b4': 0.013929708860814571,
                     'b5': 0.11667602509260178,
                     'b6': 0.5333649516105652,
                     'b7': 0.17217043042182922,
                     'b8': 0.39491915702819824,
                     'b9': 0.20575976371765137}
      normalize: [[127.0], [128.0]]
  val:
    name: coco
    img_path: /content/drive/MyDrive/Synt data test/211102_1/data/
    ann_path: /content/drive/MyDrive/Synt data test/211102_1/data/defect_annotations.json
    input_size: [1024,96] #[w,h]
    keep_ratio: True
    pipeline:
      autoaug_value: {'a1': 0.08101963251829147,
                     'a10': 0.21826782822608948,
                     'a11': 0.10481764376163483,
                     'a12': 0.6672841906547546,
                     'a2': 0.12276199460029602,
                     'a3': 0.21467134356498718,
                     'a4': 0.04544099420309067,
                     'a5': 0.2710273265838623,
                     'a6': -0.18187099695205688,
                     'a7': -0.018729938194155693,
                     'a8': -0.2271868735551834,
                     'a9': 0.24968217313289642,
                     'b0': 0.041343141347169876,
                     'b1': 0.18310876190662384,
                     'b10': 0.011901714839041233,
                     'b11': 0.07119786739349365,
                     'b12': -0.2891852557659149,
                     'b2': 0.05530325695872307,
                     'b3': 0.1800641119480133,
                     'b4': 0.013929708860814571,
                     'b5': 0.11667602509260178,
                     'b6': 0.5333649516105652,
                     'b7': 0.17217043042182922,
                     'b8': 0.39491915702819824,
                     'b9': 0.20575976371765137}
      normalize: [[127.0], [128.0]]
device:
  gpu_ids: [0]
  workers_per_gpu: 2
  batchsize_per_gpu: 30
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 3000
    ratio: 0.01
  total_epochs: 500
  lr_schedule:
    name: MultiStepLR
    milestones: [300,400,450,475]
    gamma: 0.1
  val_intervals: 20
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 20



class_names: ['defect']
