# nanodet-EfficientNet-Lite1_416
save_dir: /content/drive/MyDrive/workspace/nanodet_plus/owndata/ELG4960_Out/2/repvgg
model:
  arch:
    name: OneStageDetector
    backbone:
      name: RepVGG
      arch: A0
      out_stages: [2,3,4]
      activation: ReLU
      last_channel: 512
      deploy: False
    fpn:
      name: PAN
      in_channels: [96, 192, 512]
      out_channels: 128
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      conv_type: Conv
      input_channel: 128
      feat_channels: 128
      stacked_convs: 2
      activation: ReLU
      share_cls_reg: True
      octave_base_scale: 8
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: CocoDataset
    img_path: /content/drive/MyDrive/ELG4960_Out/2/train
    ann_path: /content/drive/MyDrive/ELG4960_Out/2/train/annotations.json
    input_size: [1024,72] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: CocoDataset
    img_path: /content/drive/MyDrive/ELG4960_Out/2/valid
    ann_path: /content/drive/MyDrive/ELG4960_Out/2/valid/annotations.json
    input_size: [1024,72] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 2
  batchsize_per_gpu: 30
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.07
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 500
    ratio: 0.01
  total_epochs: 500
  lr_schedule:
    name: MultiStepLR
    milestones: [200,300,400,450]
    gamma: 0.1
  val_intervals: 10
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['defect']
